version: '3'

tasks:

  run:
    desc: "Run an Ansible playbook"
    prompt: "Running Ansible playbook, this process will take 10+ minutes ... continue?"
    cmds:
    - python3 -m venv .venv && source .venv/bin/activate && ansible-playbook -i {{.ANSIBLE_DIR}}/bootstrap/inventory/hosts.yml {{.ANSIBLE_DIR}}/bootstrap/playbooks/initialise.yml --ask-vault-pass --ask-become-pass
