version: '3'

tasks:

  run:
    desc: "Run an Ansible playbook"
    summary: |
      Args:
        playbook: Playbook to run (required)
    prompt: "Run Ansible playbook '{{.playbook}}' from the 'bootstrap' namespace ... continue?"
    cmds:
    - ansible-playbook -i {{.ANSIBLE_DIR}}/bootstrap/inventory/hosts.yml {{.ANSIBLE_DIR}}/bootstrap/playbooks/{{.playbook}}.yml --ask-become-pass --ask-vault-pass
    requires:
      vars: ["playbook"]
