ansible_ssh_port: 22
wiki_url: git@github.com:tibia-oce/tibia-oce.github.io.git
client_url: git@github.com:tibia-oce/mythbound-client.git
server_url: git@github.com:tibia-oce/mythbound-server.git
website_url: git@github.com:tibia-oce/mythbound-website.git
launcher_url: git@github.com:tibia-oce/mythbound-launcher.git
infrastructure_url: git@github.com:tibia-oce/mythbound-infrastructure.git
map_editor_url: "git@github.com:tibia-oce/map-editor.git"
