version: '3'

tasks:

  edit:
    desc: "Edit ansible secrets"
    prompt: "Editing ansible secrets ... continue?"
    cmds:
    - ansible-vault edit ansible/bootstrap/secrets/secrets.yml

  rekey:
    desc: "Rekey ansible vault"
    prompt: "Rekeying ansible vault ... continue?"
    cmds:
    - ansible-vault rekey ansible/bootstrap/secrets/secrets.yml

  copy:
    desc: "Create a copy of the vault yaml"
    cmds:
    - cp ansible/bootstrap/secrets/not_secrets.yml ansible/bootstrap/secrets/secrets.yml

  host:
    desc: "Create a copy of the hosts yaml"
    summary: |
      Args:
        host: managed node ip address
    cmds:
    - cp ansible/bootstrap/inventory/not_hosts.yml ansible/bootstrap/inventory/hosts.yml
    - sed -i 's/0\.0\.0\.0/{{.host}}/g' ansible/bootstrap/inventory/hosts.yml
    requires:
      vars: ["host"]
