version: '3'

tasks:

  edit:
    desc: "Edit ansible secrets"
    prompt: "Editing ansible secrets ... continue?"
    cmds:
    - python3 -m venv .venv && source .venv/bin/activate
    - ansible-vault edit ansible/bootstrap/secrets/secrets.yml

  rekey:
    desc: "Rekey ansible vault"
    prompt: "Rekeying ansible vault ... continue?"
    cmds:
    - python3 -m venv .venv && source .venv/bin/activate
    - ansible-vault rekey ansible/bootstrap/secrets/secrets.yml

  copy:
    desc: "Create a copy of the hosts yaml"
    summary: |
      Args:
        host: managed node ip address
        github_username: GitHub username
        github_pat: GitHub personal access token
    cmds:
    - cp ansible/bootstrap/secrets/not_secrets.yml ansible/bootstrap/secrets/secrets.yml
    - cp ansible/bootstrap/inventory/not_hosts.yml ansible/bootstrap/inventory/hosts.yml
    - |
      sed -i 's/0\.0\.0\.0/{{.host}}/g' ansible/bootstrap/inventory/hosts.yml
    - |
      sed -i 's/github_username:.*/github_username: "{{.github_username}}"/' ansible/bootstrap/inventory/hosts.yml
    - |
      sed -i 's/github_pat:.*/github_pat: "{{.github_pat}}"/' ansible/bootstrap/inventory/hosts.yml
    requires:
      vars: ["host", "github_username", "github_pat"]
