- name: Update package list and upgrade all packages
  apt:
    update_cache: yes
    autoclean: yes

- name: Install essential packages
  apt:
    name:
      - lsof
      - ripgrep
      - fzf
      - ncdu
      - git
      - build-essential
      - autoconf
      - libtool
      - ca-certificates
      - curl
      - zip
      - unzip
      - tar
      - pkg-config
      - ninja-build
      - ccache
      - linux-headers-{{ ansible_kernel }}
      - xclip
      - build-essential
      - pkg-config
      - cmake
      - ninja-build
      - libgl-dev
      - libx11-dev
      - libxext-dev
      - libxi-dev
      - libxrandr-dev
      - libxrender-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev
      - libfuse2
      - fuse
    state: present

- name: Remove existing cmake package
  apt:
    name: cmake
    state: absent

- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present

- name: Install cmake via snap
  command: snap install cmake --classic

- name: Update package list
  apt:
    update_cache: yes

- name: Install gcc-12 and g++-12
  apt:
    name:
      - gcc-12
      - g++-12
    state: present

- name: Set gcc-12 as default gcc
  command: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12

- name: Set gcc-12 as default compiler
  command: update-alternatives --set gcc /usr/bin/gcc-12

- name: Ensure Ubuntu desktop is installed
  apt:
    name:
      - ubuntu-desktop
      - gnome-shell
      - open-vm-tools
      - open-vm-tools-desktop
    state: present
    update_cache: yes
