- name: Install Zsh
  apt:
    name: zsh
    state: present

- name: Change default shell to Zsh for the current user
  shell: chsh -s "$(which zsh)" "{{ ansible_user }}"
  become: true
  become_user: root

- name: Install Oh My Zsh
  become: true
  become_user: "{{ ansible_user }}"
  shell: |
    curl -Lo install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    sh install.sh --unattended
  args:
    creates: /home/{{ ansible_user }}/.oh-my-zsh

- name: Install powerlevel10k theme
  become: true
  become_user: "{{ ansible_user }}"
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Set Oh My Zsh theme to 'powerlevel10k'
  become: true
  become_user: "{{ ansible_user }}"
  lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    regexp: "^ZSH_THEME="
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

- name: Ensure .zshrc is sourced in the Zsh profile
  become: true
  become_user: "{{ ansible_user }}"
  lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    regexp: "^source"
    line: "source /home/{{ ansible_user }}/.zshrc"
    state: present

- name: Remove Oh My Zsh installation script
  become: true
  become_user: "{{ ansible_user }}"
  file:
    path: "/home/{{ ansible_user }}/install.sh"
    state: absent

- name: Copy custom .zshrc template from control node to remote
  become: true
  become_user: "{{ ansible_user }}"
  template:
    src: templates/zsh/zshrc.j2
    dest: "/home/{{ ansible_user }}/.zshrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Copy .p10k.zsh file into home
  become: true
  become_user: "{{ ansible_user }}"
  copy:
    src: templates/zsh/p10k.zsh.j2
    dest: "/home/{{ ansible_user }}/.p10k.zsh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
- name: Install psutil Python package for dconf module
  become: true
  apt:
    name: python3-psutil
    state: present

- name: Ensure Desktop directory exists
  become: true
  become_user: "{{ ansible_user }}"
  file:
    path: "/home/{{ ansible_user }}/Desktop"
    state: directory
    mode: "0755"

- name: Ensure Desktop directory exists
  become: true
  become_user: "{{ ansible_user }}"
  file:
    path: "/home/{{ ansible_user }}/Desktop"
    state: directory
    mode: "0755"

- name: Create basic Terminal desktop shortcut
  become: true
  become_user: "{{ ansible_user }}"
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Name=Terminal
      Exec=gnome-terminal
      Icon=utilities-terminal
      Terminal=false
    dest: "/home/{{ ansible_user }}/Desktop/terminal.desktop"
    mode: "0755"

- name: Mark desktop shortcut as trusted
  become: true
  become_user: "{{ ansible_user }}"
  shell: gio set ~/Desktop/terminal.desktop metadata::trusted true
  changed_when: true
